language: python
python:
  - "2.7"
jdk:
  - oraclejdk8
sudo: false
cache: pip
addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-installer
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - python-numpy
      - python-scipy
      - python-matplotlib
      - ipython
      - ipython-notebook
      - python-panda
      - python-symp
      - python-nose
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python setup.py build
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export PATH=/usr/lib/jvm/java-8-oracle/jre/bin/:$PATH
  - nosetests
