language: python
python:
  - "2.7"
sudo: false
cache: pip
addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - openjdk-8-jdk
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - python-numpy
      - python-scipy
      - python-matplotli
      - ipytho
      - ipython-noteboo
      - python-panda
      - python-symp
      - python-nose
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - jdk_switcher use oraclejdk8
  - python setup.py build
  - nosetests
