language: python
python:
  - "2.7"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - python-numpy
      - python-scipy
      - python-matplotli
      - ipytho
      - ipython-noteboo
      - python-panda
      - python-symp
      - python-nose
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python setup.py build
  - nosetests
